FROM node:18-alpine AS deps

RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package*.json ./
COPY gsap-bonus.tgz ./
RUN npm install
FROM node:18-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ARG NEXT_PUBLIC_API_URL_BASE
ARG NEXT_PUBLIC_MAPBOX_ACCESIBILITY_STYLES_TOKEN
ARG NEXT_PUBLIC_MAPBOX_STYLES_TOKEN
ARG NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN
ARG NEXT_PUBLIC_MAPBOX_STYLES_MINIMAP_TOKEN
ARG NEXT_PUBLIC_GTM_ID
ARG BE_EMAIL_FROM
ARG BE_SMTP_HOST
ARG BE_SMTP_USER_NAME
ARG BE_SMTP_PASSWORD
ARG NEXT_PUBLIC_IS_DEV

ENV NEXT_PUBLIC_API_URL_BASE ${NEXT_PUBLIC_API_URL_BASE}
ENV NEXT_PUBLIC_MAPBOX_ACCESIBILITY_STYLES_TOKEN ${NEXT_PUBLIC_MAPBOX_ACCESIBILITY_STYLES_TOKEN}
ENV NEXT_PUBLIC_MAPBOX_STYLES_TOKEN ${NEXT_PUBLIC_MAPBOX_STYLES_TOKEN}
ENV NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN ${NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN}
ENV NEXT_PUBLIC_MAPBOX_STYLES_MINIMAP_TOKEN ${NEXT_PUBLIC_MAPBOX_STYLES_MINIMAP_TOKEN}
ENV NEXT_PUBLIC_GTM_ID ${NEXT_PUBLIC_GTM_ID}
ENV BE_EMAIL_FROM ${BE_EMAIL_FROM}
ENV BE_SMTP_HOST ${BE_SMTP_HOST}
ENV BE_SMTP_USER_NAME ${BE_SMTP_USER_NAME}
ENV BE_SMTP_PASSWORD ${BE_SMTP_PASSWORD}
ENV NEXT_TELEMETRY_DISABLED 1

RUN npm run build

FROM node:18-alpine AS runner
WORKDIR /app

ENV NEXT_PUBLIC_IS_DEV ${NEXT_PUBLIC_IS_DEV}
ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder --chown=nextjs:nodejs /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

USER nextjs

EXPOSE 3000

ENV PORT 3000

CMD ["npm", "start"]
